musinsa_prj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls,),
    path('', include('musinsa_webapp.urls')),


]

musinsa_webapp/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'musinsa_webapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('get_point/', views.get_point, name='get_point'),
    # path('simple_upload/',views.simple_upload, name ='simple_upload'),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

musinsa_webapp/models.py
from django.db import models

# Create your models here.
class ImageUploadModel(models.Model):
    # blank=True : Form에서 빈 채로 저장되는 것을 허용 (views.py에서 활용한 .is_valid() 함수가 검증 진행 시)
    description = models.CharField(max_length=255, blank=True)
    # upload_to : 저장될 파일의 경로를 지정 (ex. ‘images/2020/02/21/test_image.jpg’)
    document = models.ImageField(upload_to='images/%Y/%m/%d')
    # auto_now_add : 자동으로 저장되는 시점을 기준으로 현재 시간을 세팅
    uploaded_at = models.DateTimeField(auto_now_add=True)

musinsa_webapp/forms.py
from django import forms
from .models import ImageUploadModel

class SimpleUploadForm(forms.Form):
    title = forms.CharField(max_length=50)
# ImageField Inherits all attributes and methods from FileField, but also validates that the uploaded object is a valid image.
# file = forms.FileField()
    image = forms.ImageField()

class ImageUploadForm(forms.ModelForm):
# Form을 통해 받아들여야 할 데이터가 명시되어 있는 메타 데이터 (DB 테이블을 연결)
    class Meta:
        model = ImageUploadModel
        # Form을 통해 사용자로부터 입력 받으려는 Model Class의 field 리스트
        fields = ('description', 'document', ) # uploaded_at

musinsa_webapp/views.py
from django.shortcuts import render, redirect
from .forms import SimpleUploadForm, ImageUploadForm
from django.core.files.storage import FileSystemStorage
from django.conf import settings
from .get_point import predict_fn

# Create your views here.

def index(request):
    return render(request, 'musinsa_webapp/index.html', {})

def simple_upload(request):
    if request.method == 'POST':
        # print(request.POST) : <QueryDict: {'csrfmiddlewaretoken': [‘~~~’], 'title': ['upload_1']}>
        # print(request.FILES) : <MultiValueDict: {'image': [<InMemoryUploadedFile: ses.jpg (image/jpeg)>]}>
        # 비어있는 Form에 사용자가 업로드한 데이터를 넣고 검증합니다.
        form = SimpleUploadForm(request.POST, request.FILES)

        if form.is_valid():
            myfile = request.FILES['image'] # 'ses.jpg'
            fs = FileSystemStorage()
            filename = fs.save(myfile.name, myfile) # 경로명을 포함한 파일명 & 파일 객체
            # 업로드된 이미지 파일의 URL을 얻어내 Template에게 전달
            uploaded_file_url = fs.url(filename) # '/media/ses.jpg'

            context = {'form': form, 'uploaded_file_url': uploaded_file_url} # filled form
            return render(request, 'musinsa_webapp/simple_upload.html', context)

    else: # request.method == 'GET' (DjangoBasic 실습과 유사한 방식입니다.)
        form = SimpleUploadForm()
        context = {'form': form} # empty form
        return render(request, 'musinsa_webapp/simple_upload.html', context)

def get_point(request):
    if request.method == 'POST' :
        # 비어있는 Form에 사용자가 업로드한 데이터를 넣고 검증합니다.
        form = ImageUploadForm(request.POST, request.FILES) # filled form
        if form.is_valid():
             # Form에 채워진 데이터를 DB에 실제로 저장하기 전에 변경하거나 추가로 다른 데이터를 추가할 수 있음
            post = form.save(commit=False)

            post.save() # DB에 실제로 Form 객체('form')에 채워져 있는 데이터를 저장
	    # post는 save() 후 DB에 저장된 ImageUploadModel 클래스 객체 자체를 갖고 있게 됨 (record 1건에 해당)

            imageURL = settings.MEDIA_URL + form.instance.document.name
	    # document : ImageUploadModel Class에 선언되어 있는 “document”에 해당
            # print(form.instance, form.instance.document.name, form.instance.document.url)
            # cv_detect_face(settings.MEDIA_ROOT_URL + imageURL) # 추후 구현 예정
            predict_result=predict_fn(settings.MEDIA_ROOT_URL + imageURL)

            context = {'form':form,
               'post':post,
               'predict_result' : predict_result}

            return render(request, 'musinsa_webapp/get_point.html', context)

    else:
         form = ImageUploadForm() # empty form
         return render(request, 'musinsa_webapp/get_point.html', {'form':form})

musinsa_webapp/templates/musinsa_webapp/get_point.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>MUSINSA PROJECT</title>
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />

    <!--상단에 네이게이션 바 -->

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
          <a class="navbar-brand" href="{% url 'musinsa_webapp:index' %}">MUSINSA STORE</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                  <!-- <li class="nav-item"><a class="nav-link active" aria-current="page" href="http://127.0.0.1:8000/home">Home</a></li> -->
                  <li class="nav-item"><a class="nav-link" href="{% url 'musinsa_webapp:index' %}">Home</a></li>
                  <li class="nav-item"><a class="nav-link active" href="{% url 'musinsa_webapp:get_point' %}">Review</a></li>
                  <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
              </ul>
          </div>
      </div>
    </nav>

  <body>

    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Upload</button>
    </form>

    {% if post %}
      <!-- post.document : ImageUploadModel Class에 선언되어 있는 "document"에 해당 (브라우저 확인) -->
      <img src="{{ post.document.url }}">
      <p>Uploaded file @ : <a href="{{ post.document.url }}">{{ post.document }}</a></p>
    {% endif %}
    <h1>{{ predict_result }}</h1>

    <p><a href="{% url 'musinsa_webapp:get_point' %}">Return to home</a></p>

</body>

</html>

musinsa_webapp/templates/musinsa_webapp/index.html
{% load static %}
<!DOCTYPE html>


<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>MUSINSA PROJECT</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="{% url 'musinsa_webapp:index' %}">MUSINSA STORE</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <!-- <li class="nav-item"><a class="nav-link active" aria-current="page" href="http://127.0.0.1:8000/home">Home</a></li> -->
                        <li class="nav-item"><a class="nav-link active" href="{% url 'musinsa_webapp:index' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'musinsa_webapp:get_point' %}">Review</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Header - set the background image for the header in the line below-->
        <header class="py-5 bg-image-full" style="background-image: url('https://source.unsplash.com/wfh8dDlNFOk/1600x900')">
            <div class="text-center my-5">
                <img class="img-fluid rounded-circle mb-4" src="https://media-exp1.licdn.com/dms/image/C4E0BAQG2bqo_zjZZkA/company-logo_200_200/0/1600236155546?e=2159024400&v=beta&t=njsRu1IlR5TmVxTUgM5pym2xffiCrTu-Lw7_EfuLvqU" alt="..." />
                <h1 class="text-white fs-3 fw-bolder">MUSINSA PROJECT</h1>
                <p class="text-white-50 mb-0">STYLE 후기 적립금 DL</p>
            </div>
        </header>
        <!-- Content section-->
        <section class="py-5">
            <div class="container my-5">
                <div class="row justify-content-center">
                    <div class="col-lg-6">
                        <h2>서비스 소개</h2>
                        <p class="lead">스타일 후기의 사진을 딥러닝해서, 포인트 지급 기준에 부합하는지 학습시킴으로써 서비스 향상을 목표로 진행함</p>
                        <p class="mb-0">The universe is almost 14 billion years old, and, wow! Life had no problem starting here on Earth! I think it would be inexcusably egocentric of us to suggest that we're alone in the universe.</p>
                    </div>
                </div>
            </div>

        </section>
        <!-- Image element - set the background image for the header in the line below-->
        <!-- <div class="py-5 bg-image-full" style="background-image: url('https://source.unsplash.com/4ulffa6qoKA/1200x800')"> -->

        <img class="py-5 bg-image-full" src="/static/assets/ex_img.png" style="margin-left: auto; margin-right: auto; display: block;"/>
            <!-- Put anything you want here! The spacer below with inline CSS is just for demo purposes!-->
            <!-- <div style="height: 20rem"></div>
        </div> -->
        <!-- Content section-->
        <section class="py-5">
            <div class="container my-5">
                <div class="row justify-content-center">
                    <div class="col-lg-6">
                        <h2>Engaging Background Images</h2>
                        <p class="lead">The background images used in this template are sourced from Unsplash and are open source and free to use.</p>
                        <p class="mb-0">I can't tell you how many people say they were turned off from science because of a science teacher that completely sucked out all the inspiration and enthusiasm they had for the course.</p>
                    </div>
                </div>
            </div>
        </section>
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; 멋쟁이성곤처럼.team</p></div>
            <p class="m-0 text-center text-white">(주) Ryu corporation</p>
          </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

musinsa_webapp/templates/musinsa_webapp/simple_upload.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Opencv-Django</title>
  </head>
  <body>
    <h1>Upload your image file.</h1>

    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Upload</button>
    </form>

    {% if uploaded_file_url %}
      <img src="{{ uploaded_file_url }}">
      <p>Uploaded file @ : <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
    {% endif %}

    <p><a href="{% url 'musinsa_webapp:simple_upload' %}">Return to home</a></p>
  </body>
</html>